# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # align gh-pages into main branch
  align-branch:
    runs-on: ubuntu-latest
    steps:
     - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git checkout gh-pages
        git pull origin main
